## House Price Prdiction
#### import important libraries

In [97]:
# import libraries we will use
import warnings
warnings.filterwarnings('ignore')

# matplotlib for plotting
from matplotlib import pyplot as plt
import matplotlib
# matplotlib.style.use('ggplot')
%matplotlib inline
import time

# pandas for dataframes
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# numpy for linear algebra
import numpy as np

# sklearn for machine learning libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [98]:
# load da set into a pandas dataframe
data = pd.read_csv('./kingcounty_house_data.csv')

In [99]:
data.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900.0         3       1.00         1180   
1  6414100192  20141209T000000   538000.0         3       2.25         2570   
2  5631500400  20150225T000000   180000.0         2       1.00          770   
3  2487200875  20141209T000000   604000.0         4       3.00         1960   
4  1954400510  20150218T000000   510000.0         3       2.00         1680   
5  7237550310  20140512T000000  1225000.0         4       4.50         5420   
6  1321400060  20140627T000000   257500.0         3       2.25         1715   
7  2008000270  20150115T000000   291850.0         3       1.50         1060   
8  2414600126  20150415T000000   229500.0         3       1.00         1780   
9  3793500160  20150312T000000   323000.0         3       2.50         1890   

   sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0      5650     1.0           0     0          3      7        1180   
1      7242     2.0           0     0          3      7        2170   
2     10000     1.0           0     0          3      6         770   
3      5000     1.0           0     0          5      7        1050   
4      8080     1.0           0     0          3      8        1680   
5    101930     1.0           0     0          3     11        3890   
6      6819     2.0           0     0          3      7        1715   
7      9711     1.0           0     0          3      7        1060   
8      7470     1.0           0     0          3      7        1050   
9      6560     2.0           0     0          3      7        1890   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   
5           1530      2001             0    98053  47.6561 -122.005   
6              0      1995             0    98003  47.3097 -122.327   
7              0      1963             0    98198  47.4095 -122.315   
8            730      1960             0    98146  47.5123 -122.337   
9              0      2003             0    98038  47.3684 -122.031   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  
5           4760      101930  
6           2238        6819  
7           1650        9711  
8           1780        8113  
9           2390        7570

In [100]:
data.shape

(21613, 21)

In [101]:
price=data.price

In [102]:
price.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [103]:
data.drop("price",1,inplace=True)

In [104]:
Id=data.id

In [105]:
data.drop("id",1,inplace=True)

In [106]:
data.drop("date",1,inplace=True)

In [107]:
data.head(10)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   
2         2       1.00          770     10000     1.0           0     0   
3         4       3.00         1960      5000     1.0           0     0   
4         3       2.00         1680      8080     1.0           0     0   
5         4       4.50         5420    101930     1.0           0     0   
6         3       2.25         1715      6819     2.0           0     0   
7         3       1.50         1060      9711     1.0           0     0   
8         3       1.00         1780      7470     1.0           0     0   
9         3       2.50         1890      6560     2.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   
2          3      6         770              0      1933             0   
3          5      7        1050            910      1965             0   
4          3      8        1680              0      1987             0   
5          3     11        3890           1530      2001             0   
6          3      7        1715              0      1995             0   
7          3      7        1060              0      1963             0   
8          3      7        1050            730      1960             0   
9          3      7        1890              0      2003             0   

   zipcode      lat     long  sqft_living15  sqft_lot15  
0    98178  47.5112 -122.257           1340        5650  
1    98125  47.7210 -122.319           1690        7639  
2    98028  47.7379 -122.233           2720        8062  
3    98136  47.5208 -122.393           1360        5000  
4    98074  47.6168 -122.045           1800        7503  
5    98053  47.6561 -122.005           4760      101930  
6    98003  47.3097 -122.327           2238        6819  
7    98198  47.4095 -122.315           1650        9711  
8    98146  47.5123 -122.337           1780        8113  
9    98038  47.3684 -122.031           2390        7570

In [108]:
data.bedrooms.unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33])

In [109]:
data.bathrooms.unique()

array([ 1.  ,  2.25,  3.  ,  2.  ,  4.5 ,  1.5 ,  2.5 ,  1.75,  2.75,
        3.25,  4.  ,  3.5 ,  0.75,  4.75,  5.  ,  4.25,  3.75,  0.  ,
        1.25,  5.25,  6.  ,  0.5 ,  5.5 ,  6.75,  5.75,  8.  ,  7.5 ,
        7.75,  6.25,  6.5 ])

In [110]:
data.sqft_living.unique()

array([1180, 2570,  770, ..., 3087, 3118, 1425])

In [111]:
data[data.sqft_living.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [112]:
data[data.sqft_lot.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [113]:
data[data.floors.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [114]:
data[data.waterfront.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [115]:
data.waterfront.unique()

array([0, 1])

In [116]:
data[data.view.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [117]:
data.view.unique()

array([0, 3, 4, 2, 1])

In [118]:
data[data.condition.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [119]:
data[data.grade.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [120]:
data[data.sqft_above.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [121]:
data[data.yr_built.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [122]:
data[data.yr_renovated.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [123]:
data[data.lat.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [124]:
data[data.long.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [125]:
data[data.sqft_living15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [126]:
data[data.sqft_lot15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [127]:
data.drop("sqft_living15",1,inplace=True)

In [128]:
data.drop("sqft_lot15",1,inplace=True)

In [129]:
data.drop("grade",1,inplace=True)

In [130]:
# data.drop("waterfront",1,inplace=True)

In [131]:
# data.drop("sqft_above",1,inplace=True)

In [132]:
train = data.ix[0:15000]
test= data.ix[15001:]

In [133]:
target_value=  price

In [134]:
target_value.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [135]:
target=target_value[0:15001]

In [136]:
target.shape

(15001,)

In [137]:
train.shape

(15001, 15)

In [138]:
test.shape

(6612, 15)

In [139]:
start=time.time()

In [140]:
clf = RandomForestClassifier(n_estimators=10)

In [141]:
clf=clf.fit(train, target)

In [142]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

bedrooms  :  0.0430610541296
bathrooms  :  0.0568122007789
sqft_living  :  0.108247217114
sqft_lot  :  0.122873478226
floors  :  0.0205555747583
waterfront  :  0.00125696434473
view  :  0.013868878808
condition  :  0.036938571121
sqft_above  :  0.110469094076
sqft_basement  :  0.0491588288495
yr_built  :  0.108775976806
yr_renovated  :  0.0107788489721
zipcode  :  0.0721844002904
lat  :  0.126126858695
long  :  0.11889205303


In [143]:
Output = clf.predict(test)


In [144]:
end=time.time()

In [145]:
elapsed = end - start
print(elapsed)

19.124377012252808


In [146]:
homeId=Id[15001:]

In [147]:
homeId.shape

(6612,)

In [148]:
result = pd.DataFrame(columns=['Id', 'price'])

In [149]:
result['Id'] = homeId
result['price'] = Output.astype(int)

In [150]:
# result.drop("Sprice",1,inplace=True)

In [151]:
result.to_csv('HousingPrice.csv', index=False)

In [152]:
print(result.head(10)) 

               Id    price
15001  7504021310   607000
15002  7504021310   607000
15003  8024201795   486700
15004  8638500170   355000
15005  5437400630   625000
15006  9264000010   359000
15007  3832600080   215500
15008  9477001350   390000
15009   809001060   410500
15010  2771604120  1300000


In [156]:
ground_truth=target_value[15001:]

In [157]:
ground_truth.shape

(6612,)

In [158]:
mean_squared_error(ground_truth,result.price)

76457808232.730194

In [159]:
accuracy_score(ground_truth,result.price)

0.0071082879612825167

In [160]:
mean_absolute_error(ground_truth,result.price)

149269.591954023

In [161]:
Resultant = pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [162]:
Resultant['ground_truth']=ground_truth

In [163]:
Resultant['Estimated']=result['price']

In [164]:
print(Resultant.head(20))

       ground_truth  Estimated
15001      525000.0     607000
15002      745000.0     607000
15003      397000.0     486700
15004      233000.0     355000
15005      625000.0     625000
15006      535000.0     359000
15007      270000.0     215500
15008      360000.0     390000
15009     1105000.0     410500
15010      970000.0    1300000
15011      915000.0     799000
15012      412000.0     385000
15013      265000.0     253000
15014      426000.0     425000
15015      266000.0     229000
15016      325000.0     350000
15017      615000.0     330000
15018      310000.0     210000
15019      340000.0     310000
15020      562500.0     527500


In [165]:
total=Resultant['ground_truth'].sum()

In [166]:
total_estimated=Resultant['Estimated'].sum()

In [167]:
print(abs(total_estimated-total)/total)

0.15688978817865495


In [168]:
# x = Resultant['ground_truth']
# y = Resultant['Estimated']
# plt.plot(x, y)


## APPLYING RANDOMIZATION

In [169]:
df=pd.read_csv('./kingcounty_house_data.csv')
sample_data=df.take(np.random.permutation(len(df))[:2500])

In [170]:
sample_data.head(10)

id             date     price  bedrooms  bathrooms  \
9764   7982600030  20140812T000000  219000.0         3       1.50   
12134  2767604170  20150406T000000  975000.0         3       3.00   
1322   7772400160  20141024T000000  279950.0         3       1.75   
18624  2287600035  20140625T000000  595888.0         3       1.75   
14866  7936800150  20140702T000000  394500.0         4       2.50   
5792   7522500020  20140527T000000  730001.0         3       2.00   
13509  3432501395  20140924T000000  551000.0         4       2.75   
19794  1972201963  20140616T000000  523950.0         3       2.25   
12177  7010700550  20141114T000000  595000.0         3       2.50   
13885  1862400087  20150313T000000  475000.0         3       1.75   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
9764          1200     12000     1.0           0     0          3      7   
12134         1850      5000     1.5           0     0          2      6   
1322          1510     11234     1.0           0     0          3      7   
18624         1870      9000     1.0           0     0          5      9   
14866         3002      6042     2.0           0     0          3      8   
5792          1840      4750     1.0           0     0          5      7   
13509         2170      5988     2.0           0     0          3      8   
19794         1420      1282     3.0           0     0          3      8   
12177         2030      5100     2.0           0     0          3      7   
13885         1520      8100     1.0           0     0          5      6   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
9764         1200              0      1986             0    98001  47.2680   
12134        1850              0      1900             0    98107  47.6711   
1322         1210            300      1965             0    98155  47.7571   
18624        1870              0      1958             0    98177  47.7203   
14866        3002              0      2004             0    98055  47.4231   
5792         1010            830      1951             0    98117  47.6862   
13509        2170              0      2014             0    98155  47.7484   
19794        1420              0      2006             0    98103  47.6533   
12177        2030              0      2008             0    98199  47.6594   
13885         760            760      1945             0    98117  47.6966   

          long  sqft_living15  sqft_lot15  
9764  -122.245           1200        9405  
12134 -122.386           1360        2500  
1322  -122.328           2080        9076  
18624 -122.361           2030        8160  
14866 -122.186           2566        6390  
5792  -122.395           1760        5510  
13509 -122.317           1170        8147  
19794 -122.346           1530        1280  
12177 -122.397           1790        4380  
13885 -122.375           1040        8100

In [171]:
sample_price=sample_data.price

In [172]:
sample_price.head()

9764     219000.0
12134    975000.0
1322     279950.0
18624    595888.0
14866    394500.0
Name: price, dtype: float64

In [173]:
train, test = train_test_split(sample_data, test_size = 0.3)

In [174]:
train_price=train.price

In [175]:
test_price=test.price

In [176]:
train.drop("price",1,inplace=True)

In [177]:
train.drop("date",1,inplace=True)

In [178]:
train.drop("grade",1,inplace=True)

In [179]:
train.drop("sqft_living15",1,inplace=True)

In [180]:
train.drop("sqft_lot15",1,inplace=True)

In [181]:
test.drop("price",1,inplace=True)

In [182]:
test.drop("date",1,inplace=True)

In [183]:
test.drop("grade",1,inplace=True)

In [184]:
test.drop("sqft_living15",1,inplace=True)

In [185]:
test.drop("sqft_lot15",1,inplace=True)

In [186]:
start=time.time()

In [187]:
clf = RandomForestClassifier()

In [188]:
clf=clf.fit(train, train_price)

In [189]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.102873144032
bedrooms  :  0.0391055476635
bathrooms  :  0.0555651334298
sqft_living  :  0.0944621372863
sqft_lot  :  0.10230864315
floors  :  0.0211675271406
waterfront  :  0.00197582439947
view  :  0.0134766900487
condition  :  0.029555888055
sqft_above  :  0.0988953010484
sqft_basement  :  0.0431873628898
yr_built  :  0.0970813042702
yr_renovated  :  0.00944850313435
zipcode  :  0.0755353688488
lat  :  0.113410347611
long  :  0.101951276992


In [190]:
Output = clf.predict(test)

In [191]:
end=time.time()

In [192]:
elapsed = end - start
print(elapsed)

1.513017177581787


In [193]:
Random_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [194]:
Random_Result['ground_truth']=test_price

In [195]:
Random_Result['Estimated']=Output.astype(int)

In [196]:
print(Random_Result.head(10))

       ground_truth  Estimated
4851       988830.0     695000
18619      640000.0     540000
20307      665000.0     282000
7224       456500.0     278000
8626       425000.0     208800
1958       429800.0     442500
4450       620000.0     470000
19922      455000.0     379950
10908      335900.0     233000
13886      575000.0     437500


In [197]:
mean_squared_error(test_price,Random_Result['Estimated'])

85579926626.262665

In [198]:
mean_absolute_error(test_price,Random_Result['Estimated'])

156803.01199999999

In [199]:
total=Random_Result['ground_truth'].sum()

In [200]:
total_estimated=Random_Result['Estimated'].sum()

In [201]:
print(abs(total_estimated-total)/total)

0.1829427899055436
