## House Price Prdiction
#### import important libraries

In [1]:
# import libraries we will use
import warnings
warnings.filterwarnings('ignore')

# matplotlib for plotting
from matplotlib import pyplot as plt
import matplotlib
# matplotlib.style.use('ggplot')
%matplotlib inline
import time

# pandas for dataframes
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# numpy for linear algebra
import numpy as np

# sklearn for machine learning libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [2]:
# load da set into a pandas dataframe
data = pd.read_csv('./kingcounty_house_data.csv')

In [3]:
data.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900.0         3       1.00         1180   
1  6414100192  20141209T000000   538000.0         3       2.25         2570   
2  5631500400  20150225T000000   180000.0         2       1.00          770   
3  2487200875  20141209T000000   604000.0         4       3.00         1960   
4  1954400510  20150218T000000   510000.0         3       2.00         1680   
5  7237550310  20140512T000000  1225000.0         4       4.50         5420   
6  1321400060  20140627T000000   257500.0         3       2.25         1715   
7  2008000270  20150115T000000   291850.0         3       1.50         1060   
8  2414600126  20150415T000000   229500.0         3       1.00         1780   
9  3793500160  20150312T000000   323000.0         3       2.50         1890   

   sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0      5650     1.0           0     0          3      7        1180   
1      7242     2.0           0     0          3      7        2170   
2     10000     1.0           0     0          3      6         770   
3      5000     1.0           0     0          5      7        1050   
4      8080     1.0           0     0          3      8        1680   
5    101930     1.0           0     0          3     11        3890   
6      6819     2.0           0     0          3      7        1715   
7      9711     1.0           0     0          3      7        1060   
8      7470     1.0           0     0          3      7        1050   
9      6560     2.0           0     0          3      7        1890   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   
5           1530      2001             0    98053  47.6561 -122.005   
6              0      1995             0    98003  47.3097 -122.327   
7              0      1963             0    98198  47.4095 -122.315   
8            730      1960             0    98146  47.5123 -122.337   
9              0      2003             0    98038  47.3684 -122.031   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  
5           4760      101930  
6           2238        6819  
7           1650        9711  
8           1780        8113  
9           2390        7570

In [4]:
data.shape

(21613, 21)

In [5]:
price=data.price

In [6]:
price.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [7]:
data.drop("price",1,inplace=True)

In [8]:
Id=data.id

In [9]:
data.drop("id",1,inplace=True)

In [10]:
data.drop("date",1,inplace=True)

In [11]:
data.head(10)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   
2         2       1.00          770     10000     1.0           0     0   
3         4       3.00         1960      5000     1.0           0     0   
4         3       2.00         1680      8080     1.0           0     0   
5         4       4.50         5420    101930     1.0           0     0   
6         3       2.25         1715      6819     2.0           0     0   
7         3       1.50         1060      9711     1.0           0     0   
8         3       1.00         1780      7470     1.0           0     0   
9         3       2.50         1890      6560     2.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   
2          3      6         770              0      1933             0   
3          5      7        1050            910      1965             0   
4          3      8        1680              0      1987             0   
5          3     11        3890           1530      2001             0   
6          3      7        1715              0      1995             0   
7          3      7        1060              0      1963             0   
8          3      7        1050            730      1960             0   
9          3      7        1890              0      2003             0   

   zipcode      lat     long  sqft_living15  sqft_lot15  
0    98178  47.5112 -122.257           1340        5650  
1    98125  47.7210 -122.319           1690        7639  
2    98028  47.7379 -122.233           2720        8062  
3    98136  47.5208 -122.393           1360        5000  
4    98074  47.6168 -122.045           1800        7503  
5    98053  47.6561 -122.005           4760      101930  
6    98003  47.3097 -122.327           2238        6819  
7    98198  47.4095 -122.315           1650        9711  
8    98146  47.5123 -122.337           1780        8113  
9    98038  47.3684 -122.031           2390        7570

In [12]:
data.bedrooms.unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33])

In [13]:
data.bathrooms.unique()

array([ 1.  ,  2.25,  3.  ,  2.  ,  4.5 ,  1.5 ,  2.5 ,  1.75,  2.75,
        3.25,  4.  ,  3.5 ,  0.75,  4.75,  5.  ,  4.25,  3.75,  0.  ,
        1.25,  5.25,  6.  ,  0.5 ,  5.5 ,  6.75,  5.75,  8.  ,  7.5 ,
        7.75,  6.25,  6.5 ])

In [14]:
data.sqft_living.unique()

array([1180, 2570,  770, ..., 3087, 3118, 1425])

In [15]:
data[data.sqft_living.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [16]:
data[data.sqft_lot.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [17]:
data[data.floors.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [18]:
data[data.waterfront.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [19]:
data.waterfront.unique()

array([0, 1])

In [20]:
data[data.view.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [21]:
data.view.unique()

array([0, 3, 4, 2, 1])

In [22]:
data[data.condition.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [23]:
data[data.grade.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [24]:
data[data.sqft_above.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [25]:
data[data.yr_built.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [26]:
data[data.yr_renovated.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [27]:
data[data.lat.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [28]:
data[data.long.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [29]:
data[data.sqft_living15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [30]:
data[data.sqft_lot15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [31]:
data.drop("sqft_living15",1,inplace=True)

In [32]:
data.drop("sqft_lot15",1,inplace=True)

In [33]:
data.drop("grade",1,inplace=True)

In [34]:
# data.drop("waterfront",1,inplace=True)

In [35]:
# data.drop("sqft_above",1,inplace=True)

In [36]:
train = data.ix[0:15000]
test= data.ix[15001:]

In [37]:
target_value=  price

In [38]:
target_value.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [39]:
target=target_value[0:15001]

In [40]:
target.shape

(15001,)

In [41]:
train.shape

(15001, 15)

In [42]:
test.shape

(6612, 15)

In [43]:
start=time.time()

In [44]:
clf = RandomForestClassifier(n_estimators=10)

In [45]:
clf=clf.fit(train, target)

In [46]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

bedrooms  :  0.0410872597556
bathrooms  :  0.0543243504649
sqft_living  :  0.109156085744
sqft_lot  :  0.126055705191
floors  :  0.0219719627034
waterfront  :  0.00109632598626
view  :  0.0145287027246
condition  :  0.0366299996031
sqft_above  :  0.110515200901
sqft_basement  :  0.051602684619
yr_built  :  0.107103784038
yr_renovated  :  0.0106264799207
zipcode  :  0.0725489901346
lat  :  0.125704140392
long  :  0.117048327822


In [47]:
Output = clf.predict(test)


In [48]:
end=time.time()

In [49]:
elapsed = end - start
print(elapsed)

19.22363305091858


In [50]:
homeId=Id[15001:]

In [51]:
homeId.shape

(6612,)

In [52]:
result = pd.DataFrame(columns=['Id', 'price'])

In [53]:
result['Id'] = homeId
result['price'] = Output.astype(int)

In [54]:
# result.drop("Sprice",1,inplace=True)

In [55]:
result.to_csv('HousingPrice.csv', index=False)

In [56]:
print(result.head(10)) 

               Id   price
15001  7504021310  439000
15002  7504021310  439000
15003  8024201795  390000
15004  8638500170  350000
15005  5437400630  625000
15006  9264000010  294000
15007  3832600080  285000
15008  9477001350  445950
15009   809001060  885000
15010  2771604120  652500


In [57]:
ground_truth=target_value[15001:]

In [58]:
ground_truth.shape

(6612,)

In [59]:
mean_squared_error(ground_truth,result.price)

71744242595.609039

In [60]:
accuracy_score(ground_truth,result.price)

0.0068058076225045372

In [61]:
mean_absolute_error(ground_truth,result.price)

146134.53433151846

In [62]:
Resultant = pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [63]:
Resultant['ground_truth']=ground_truth

In [64]:
Resultant['Estimated']=result['price']

In [65]:
print(Resultant.head(20))

       ground_truth  Estimated
15001      525000.0     439000
15002      745000.0     439000
15003      397000.0     390000
15004      233000.0     350000
15005      625000.0     625000
15006      535000.0     294000
15007      270000.0     285000
15008      360000.0     445950
15009     1105000.0     885000
15010      970000.0     652500
15011      915000.0    1370000
15012      412000.0     415950
15013      265000.0     182000
15014      426000.0     456500
15015      266000.0     229000
15016      325000.0     549000
15017      615000.0     445000
15018      310000.0     240000
15019      340000.0     395000
15020      562500.0     430000


In [66]:
total=Resultant['ground_truth'].sum()

In [67]:
total_estimated=Resultant['Estimated'].sum()

In [68]:
print(abs(total_estimated-total)/total)

0.15639856367395275


In [69]:
# x = Resultant['ground_truth']
# y = Resultant['Estimated']
# plt.plot(x, y)


## APPLYING RANDOMIZATION

In [70]:
df=pd.read_csv('./kingcounty_house_data.csv')
sample_data=df.take(np.random.permutation(len(df))[:3000])

In [71]:
sample_data.head(10)

id             date      price  bedrooms  bathrooms  \
8933   2508800220  20150325T000000   284000.0         4       2.50   
4754   4292300010  20140527T000000   405000.0         3       1.75   
15362    59000250  20141203T000000   720000.0         3       1.50   
18718  2600140120  20140812T000000   946000.0         4       3.00   
12115  6070500055  20140506T000000   599000.0         4       2.25   
16694  8722100825  20150429T000000  1049000.0         3       2.25   
7469   6648500440  20141121T000000   319000.0         4       2.25   
12500  9211500730  20150218T000000   162000.0         3       2.25   
15548   318900080  20141010T000000   470000.0         4       1.00   
7210   2896310420  20150219T000000   615000.0         4       2.75   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
8933          1830      6360     2.0           0     0          3      8   
4754          1980      8100     1.0           0     0          4      7   
15362         2180      5000     1.0           0     3          4      8   
18718         3140      9058     1.0           0     0          3      9   
12115         2260     29930     2.0           0     0          4      8   
16694         2610      3357     2.0           0     0          4      7   
7469          2380      7400     1.0           0     0          4      8   
12500         1810      6750     1.0           0     0          3      7   
15548         1740     37238     1.5           0     0          4      7   
7210          3120     34040     2.0           0     0          3      9   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
8933         1830              0      1994             0    98031  47.4184   
4754         1310            670      1949             0    98133  47.7353   
15362        1090           1090      1941             0    98116  47.5787   
18718        2140           1000      1989             0    98006  47.5462   
12115        1400            860      1977             0    98006  47.5689   
16694        1980            630      1926             0    98112  47.6380   
7469         1760            620      1979             0    98042  47.3555   
12500        1280            530      1978             0    98023  47.2976   
15548        1740              0      1932             0    98024  47.5651   
7210         3120              0      1997             0    98010  47.3431   

          long  sqft_living15  sqft_lot15  
8933  -122.180           1830        6596  
4754  -122.331           1450        8212  
15362 -122.402           2070        5000  
18718 -122.154           2760       10018  
12115 -122.126           2770       29930  
16694 -122.306           1940        3357  
7469  -122.149           1940        7400  
12500 -122.377           1690        7770  
15548 -121.902           1810       18352  
7210  -122.030           2420       25201

In [72]:
sample_price=sample_data.price

In [73]:
sample_price.head()

8933     284000.0
4754     405000.0
15362    720000.0
18718    946000.0
12115    599000.0
Name: price, dtype: float64

In [74]:
train, test = train_test_split(sample_data, test_size = 0.3)

In [75]:
train_price=train.price

In [76]:
test_price=test.price

In [77]:
train.drop("price",1,inplace=True)

In [78]:
train.drop("date",1,inplace=True)

In [79]:
train.drop("grade",1,inplace=True)

In [80]:
train.drop("sqft_living15",1,inplace=True)

In [81]:
train.drop("sqft_lot15",1,inplace=True)

In [82]:
test.drop("price",1,inplace=True)

In [83]:
test.drop("date",1,inplace=True)

In [84]:
test.drop("grade",1,inplace=True)

In [85]:
test.drop("sqft_living15",1,inplace=True)

In [86]:
test.drop("sqft_lot15",1,inplace=True)

In [87]:
start=time.time()

In [88]:
clf = RandomForestClassifier()

In [89]:
clf=clf.fit(train, train_price)

In [90]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.106054676308
bedrooms  :  0.038432542291
bathrooms  :  0.0538032865046
sqft_living  :  0.0987889664487
sqft_lot  :  0.104187286239
floors  :  0.0258842186328
waterfront  :  0.00136997024547
view  :  0.0136038485941
condition  :  0.031182186117
sqft_above  :  0.0944746300138
sqft_basement  :  0.0479643056732
yr_built  :  0.0934640015101
yr_renovated  :  0.00949663435657
zipcode  :  0.0677039971508
lat  :  0.107699263971
long  :  0.105890185945


In [91]:
Output = clf.predict(test)

In [92]:
end=time.time()

In [93]:
elapsed = end - start
print(elapsed)

1.471203088760376


In [94]:
Random_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [95]:
Random_Result['ground_truth']=test_price

In [96]:
Random_Result['Estimated']=Output.astype(int)

In [97]:
print(Random_Result.head(10))

       ground_truth  Estimated
18809      335000.0     200000
3424       672324.0     842000
10942      475000.0     359782
4428      1670000.0    1799000
16457      810000.0     795000
15429      320000.0     312500
2837       490000.0     336500
15947      655500.0    1195000
7371       395000.0     210000
5730       250000.0     450000


In [98]:
mean_squared_error(test_price,Random_Result['Estimated'])

91342386144.534439

In [99]:
mean_absolute_error(test_price,Random_Result['Estimated'])

163234.03222222222

In [100]:
total=Random_Result['ground_truth'].sum()

In [101]:
total_estimated=Random_Result['Estimated'].sum()

In [102]:
print(abs(total_estimated-total)/total)

0.1559463415610093


## Without Randomization

In [103]:
df=pd.read_csv('./kingcounty_house_data.csv')

In [104]:
data=df[:3000]

In [105]:
price=data.price

In [106]:
train, test = train_test_split(data, test_size = 0.3)

In [107]:
train_price=train.price

In [108]:
test_price=test.price

In [109]:
train.drop("price",1,inplace=True)

In [110]:
train.drop("date",1,inplace=True)

In [111]:
train.drop("grade",1,inplace=True)

In [112]:
train.drop("sqft_living15",1,inplace=True)

In [113]:
train.drop("sqft_lot15",1,inplace=True)

In [114]:
test.drop("price",1,inplace=True)

In [115]:
test.drop("date",1,inplace=True)

In [116]:
test.drop("grade",1,inplace=True)

In [117]:
test.drop("sqft_living15",1,inplace=True)

In [118]:
test.drop("sqft_lot15",1,inplace=True)

In [119]:
start=time.time()

In [120]:
clf = RandomForestClassifier()

In [121]:
clf=clf.fit(train, train_price)

In [122]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.104232540449
bedrooms  :  0.039193631425
bathrooms  :  0.0523293415962
sqft_living  :  0.0948366483805
sqft_lot  :  0.100963938503
floors  :  0.0198970375267
waterfront  :  0.00144948067361
view  :  0.01305511531
condition  :  0.0316514223648
sqft_above  :  0.09741724721
sqft_basement  :  0.0505492370679
yr_built  :  0.0956626275521
yr_renovated  :  0.00997027844643
zipcode  :  0.0738459044408
lat  :  0.114914617207
long  :  0.100030931847


In [123]:
Output = clf.predict(test)

In [124]:
end=time.time()

In [125]:
elapsed = end - start
print(elapsed)

1.0347599983215332


In [126]:
Subset_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [127]:
Subset_Result['ground_truth']=test_price

In [128]:
Subset_Result['Estimated']=Output.astype(int)

In [129]:
total=Subset_Result['ground_truth'].sum()

In [130]:
total_estimated=Subset_Result['Estimated'].sum()

In [131]:
print(abs(total_estimated-total)/total)

0.16230217089786753
