## House Price Prdiction
#### import important libraries

In [1]:
# import libraries we will use
import warnings
warnings.filterwarnings('ignore')

# matplotlib for plotting
from matplotlib import pyplot as plt
import matplotlib
# matplotlib.style.use('ggplot')
%matplotlib inline

# seaborn for plotting
# import seaborn as sns

# pandas for dataframes
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# numpy for linear algebra
import numpy as np

# sklearn for machine learning libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [2]:
# load da set into a pandas dataframe
data = pd.read_csv('./kingcounty_house_data.csv')

In [3]:
data.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900.0         3       1.00         1180   
1  6414100192  20141209T000000   538000.0         3       2.25         2570   
2  5631500400  20150225T000000   180000.0         2       1.00          770   
3  2487200875  20141209T000000   604000.0         4       3.00         1960   
4  1954400510  20150218T000000   510000.0         3       2.00         1680   
5  7237550310  20140512T000000  1225000.0         4       4.50         5420   
6  1321400060  20140627T000000   257500.0         3       2.25         1715   
7  2008000270  20150115T000000   291850.0         3       1.50         1060   
8  2414600126  20150415T000000   229500.0         3       1.00         1780   
9  3793500160  20150312T000000   323000.0         3       2.50         1890   

   sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0      5650     1.0           0     0          3      7        1180   
1      7242     2.0           0     0          3      7        2170   
2     10000     1.0           0     0          3      6         770   
3      5000     1.0           0     0          5      7        1050   
4      8080     1.0           0     0          3      8        1680   
5    101930     1.0           0     0          3     11        3890   
6      6819     2.0           0     0          3      7        1715   
7      9711     1.0           0     0          3      7        1060   
8      7470     1.0           0     0          3      7        1050   
9      6560     2.0           0     0          3      7        1890   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   
5           1530      2001             0    98053  47.6561 -122.005   
6              0      1995             0    98003  47.3097 -122.327   
7              0      1963             0    98198  47.4095 -122.315   
8            730      1960             0    98146  47.5123 -122.337   
9              0      2003             0    98038  47.3684 -122.031   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  
5           4760      101930  
6           2238        6819  
7           1650        9711  
8           1780        8113  
9           2390        7570

In [4]:
data.shape

(21613, 21)

In [5]:
price=data.price

In [6]:
price.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [7]:
data.drop("price",1,inplace=True)

In [8]:
Id=data.id

In [9]:
data.drop("id",1,inplace=True)

In [10]:
data.drop("date",1,inplace=True)

In [11]:
data.head(10)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   
2         2       1.00          770     10000     1.0           0     0   
3         4       3.00         1960      5000     1.0           0     0   
4         3       2.00         1680      8080     1.0           0     0   
5         4       4.50         5420    101930     1.0           0     0   
6         3       2.25         1715      6819     2.0           0     0   
7         3       1.50         1060      9711     1.0           0     0   
8         3       1.00         1780      7470     1.0           0     0   
9         3       2.50         1890      6560     2.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   
2          3      6         770              0      1933             0   
3          5      7        1050            910      1965             0   
4          3      8        1680              0      1987             0   
5          3     11        3890           1530      2001             0   
6          3      7        1715              0      1995             0   
7          3      7        1060              0      1963             0   
8          3      7        1050            730      1960             0   
9          3      7        1890              0      2003             0   

   zipcode      lat     long  sqft_living15  sqft_lot15  
0    98178  47.5112 -122.257           1340        5650  
1    98125  47.7210 -122.319           1690        7639  
2    98028  47.7379 -122.233           2720        8062  
3    98136  47.5208 -122.393           1360        5000  
4    98074  47.6168 -122.045           1800        7503  
5    98053  47.6561 -122.005           4760      101930  
6    98003  47.3097 -122.327           2238        6819  
7    98198  47.4095 -122.315           1650        9711  
8    98146  47.5123 -122.337           1780        8113  
9    98038  47.3684 -122.031           2390        7570

In [12]:
data.bedrooms.unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33])

In [13]:
data.bathrooms.unique()

array([ 1.  ,  2.25,  3.  ,  2.  ,  4.5 ,  1.5 ,  2.5 ,  1.75,  2.75,
        3.25,  4.  ,  3.5 ,  0.75,  4.75,  5.  ,  4.25,  3.75,  0.  ,
        1.25,  5.25,  6.  ,  0.5 ,  5.5 ,  6.75,  5.75,  8.  ,  7.5 ,
        7.75,  6.25,  6.5 ])

In [14]:
data.sqft_living.unique()

array([1180, 2570,  770, ..., 3087, 3118, 1425])

In [15]:
data[data.sqft_living.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [16]:
data[data.sqft_lot.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [17]:
data[data.floors.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [18]:
data[data.waterfront.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [19]:
data.waterfront.unique()

array([0, 1])

In [20]:
data[data.view.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [21]:
data.view.unique()

array([0, 3, 4, 2, 1])

In [22]:
data[data.condition.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [23]:
data[data.grade.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [24]:
data[data.sqft_above.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [25]:
data[data.yr_built.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [26]:
data[data.yr_renovated.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [27]:
data[data.lat.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [28]:
data[data.long.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [29]:
data[data.sqft_living15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [30]:
data[data.sqft_lot15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [31]:
data.drop("sqft_living15",1,inplace=True)

In [32]:
data.drop("sqft_lot15",1,inplace=True)

In [33]:
data.drop("grade",1,inplace=True)

In [34]:
# data.drop("waterfront",1,inplace=True)

In [35]:
# data.drop("sqft_above",1,inplace=True)

In [36]:
train = data.ix[0:14000]
test= data.ix[14001:]

In [37]:
target_value=  price

In [38]:
target_value.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [39]:
target=target_value[0:14001]

In [40]:
target.shape

(14001,)

In [41]:
train.shape

(14001, 15)

In [42]:
test.shape

(7612, 15)

In [43]:
clf = RandomForestClassifier(n_estimators=10)

In [44]:
clf=clf.fit(train, target)

In [45]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

bedrooms  :  0.039612821507
bathrooms  :  0.0585085847563
sqft_living  :  0.109927213724
sqft_lot  :  0.124696298912
floors  :  0.0198031135323
waterfront  :  0.0012780921066
view  :  0.0161070341972
condition  :  0.0352225334727
sqft_above  :  0.109633496496
sqft_basement  :  0.0501346345082
yr_built  :  0.106067380073
yr_renovated  :  0.0100508188668
zipcode  :  0.0734616204965
lat  :  0.128856385289
long  :  0.116639972062


In [46]:
Output = clf.predict(test)


In [47]:
homeId=Id[14001:]

In [48]:
homeId.shape

(7612,)

In [49]:
result = pd.DataFrame(columns=['Id', 'price'])

In [50]:
result['Id'] = homeId
result['price'] = Output.astype(int)

In [51]:
# result.drop("Sprice",1,inplace=True)

In [52]:
result.to_csv('HousingPrice.csv', index=False)

In [53]:
print(result.head(10)) 

               Id    price
14001  2354300456   107000
14002  7789000120   230000
14003  3210200395   219000
14004  8658303065   300000
14005  4046601010   521000
14006   526059183   450000
14007  5056500210  1100000
14008  6146600175   235000
14009  6057700120   395000
14010  8651442060   215000


In [54]:
ground_truth=target_value[14001:]

In [55]:
ground_truth.shape

(7612,)

In [56]:
mean_squared_error(ground_truth,result.price)

70690616994.790726

In [57]:
accuracy_score(ground_truth,result.price)

0.0074881765633210721

In [58]:
mean_absolute_error(ground_truth,result.price)

145540.12493431423

In [59]:
Resultant = pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [60]:
Resultant['ground_truth']=ground_truth

In [61]:
Resultant['Estimated']=result['price']

In [62]:
print(Resultant.head(20))

       ground_truth  Estimated
14001      130000.0     107000
14002      229000.0     230000
14003      279900.0     219000
14004      307000.0     300000
14005      399950.0     521000
14006      405000.0     450000
14007      539950.0    1100000
14008      129000.0     235000
14009      340000.0     395000
14010      214950.0     215000
14011      450000.0     418000
14012      515000.0     615000
14013     1400000.0     762000
14014      230000.0     219950
14015      681000.0     440000
14016      255000.0     130000
14017      580000.0     519000
14018      295000.0     192000
14019      286000.0     355000
14020      425000.0     342000


In [63]:
total=Resultant['ground_truth'].sum()

In [64]:
total_estimated=Resultant['Estimated'].sum()

In [65]:
print(abs(total_estimated-total)/total)

0.15136929718145817


## APPLYING RANDOMIZATION

In [66]:
df=pd.read_csv('./kingcounty_house_data.csv')
sample_data=df.take(np.random.permutation(len(df))[:2161])

In [67]:
sample_data.head(10)

id             date     price  bedrooms  bathrooms  \
5343   1926069063  20150306T000000  585000.0         3       1.75   
9033   1186000035  20140512T000000  770000.0         3       1.75   
15497  7922720250  20150506T000000  601002.0         4       2.50   
14464    34001540  20150423T000000  573300.0         2       1.75   
15176  3223059217  20141104T000000  225000.0         2       1.00   
16659   200800480  20141106T000000  552321.0         3       2.50   
16606  8827901350  20150407T000000  685000.0         3       1.75   
8142   1853000300  20150224T000000  875000.0         3       2.75   
19347  3693901720  20140701T000000  535000.0         4       1.75   
644    7852180340  20140930T000000  430000.0         3       2.50   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
5343          1790     87213     1.0           0     0          4      7   
9033          1720      5000     1.0           0     0          3      9   
15497         2050      8094     1.0           0     0          3      8   
14464         1290      6600     1.0           0     2          3      7   
15176          940     15000     1.0           0     0          3      7   
16659         1960      8469     2.0           0     0          4      8   
16606         2720      4720     1.5           0     0          4      7   
8142          3270     39586     1.5           0     0          3     11   
19347         1420      5000     1.5           0     0          4      7   
644           2360      6699     2.0           0     0          3      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
5343         1790              0      1974             0    98077  47.7320   
9033         1720              0      1954          2014    98122  47.6157   
15497        1050           1000      1976             0    98052  47.6614   
14464         870            420      1951             0    98136  47.5310   
15176         940              0      1960             0    98055  47.4312   
16659        1960              0      1984             0    98052  47.7236   
16606        1580           1140      1925             0    98105  47.6691   
8142         3270              0      1988             0    98077  47.7310   
19347        1420              0      1945             0    98117  47.6771   
644          2360              0      2003             0    98065  47.5317   

          long  sqft_living15  sqft_lot15  
5343  -122.077           3270       39586  
9033  -122.290           2120        4188  
15497 -122.138           1990        9020  
14464 -122.390           2380        7370  
15176 -122.195           1450       15000  
16659 -122.105           2040        8189  
16606 -122.290           1660        4640  
8142  -122.078           3480       35998  
19347 -122.397           1490        5000  
644   -121.853           2360        4744

In [68]:
sample_price=sample_data.price

In [69]:
sample_price.head()

5343     585000.0
9033     770000.0
15497    601002.0
14464    573300.0
15176    225000.0
Name: price, dtype: float64

In [70]:
train, test = train_test_split(sample_data, test_size = 0.33)

In [71]:
train_price=train.price

In [72]:
test_price=test.price

In [73]:
train.drop("price",1,inplace=True)

In [74]:
train.drop("date",1,inplace=True)

In [75]:
train.drop("grade",1,inplace=True)

In [76]:
train.drop("sqft_living15",1,inplace=True)

In [77]:
train.drop("sqft_lot15",1,inplace=True)

In [78]:
test.drop("price",1,inplace=True)

In [79]:
test.drop("date",1,inplace=True)

In [80]:
test.drop("grade",1,inplace=True)

In [81]:
test.drop("sqft_living15",1,inplace=True)

In [82]:
test.drop("sqft_lot15",1,inplace=True)

In [83]:
clf = RandomForestClassifier()

In [84]:
clf=clf.fit(train, train_price)

In [85]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.11126043097
bedrooms  :  0.0420448856675
bathrooms  :  0.0538925065196
sqft_living  :  0.0941815789304
sqft_lot  :  0.0983375467447
floors  :  0.0233942283358
waterfront  :  0.000908391236467
view  :  0.0132790258689
condition  :  0.0314138677732
sqft_above  :  0.0937389550984
sqft_basement  :  0.0468782488045
yr_built  :  0.0957949195698
yr_renovated  :  0.00870903119336
zipcode  :  0.0694623439011
lat  :  0.115594679829
long  :  0.101109359557


In [86]:
Output = clf.predict(test)

In [87]:
Random_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [88]:
Random_Result['ground_truth']=test_price

In [89]:
Random_Result['Estimated']=Output.astype(int)

In [90]:
print(Random_Result.head(10))

       ground_truth  Estimated
16821      610000.0     324000
13535      249900.0     201500
15994      465000.0     650000
7855       342000.0     310000
11595      402000.0     595000
14464      573300.0     270000
3388       637000.0     650000
19211      374500.0     330000
7166       237000.0     193000
19446     1900000.0    1600000


In [91]:
mean_squared_error(test_price,Random_Result['Estimated'])

76296687019.121841

In [92]:
mean_absolute_error(test_price,Random_Result['Estimated'])

163797.11344537814

In [93]:
total=Random_Result['ground_truth'].sum()

In [94]:
total_estimated=Random_Result['Estimated'].sum()

In [95]:
print(abs(total_estimated-total)/total)

0.18246342721999845
