## House Price Prdiction
#### import important libraries

In [3]:
# import libraries we will use
import warnings
warnings.filterwarnings('ignore')

# matplotlib for plotting
from matplotlib import pyplot as plt
import matplotlib
# matplotlib.style.use('ggplot')
%matplotlib inline
import time

# pandas for dataframes
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# numpy for linear algebra
import numpy as np

# sklearn for machine learning libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [4]:
# load da set into a pandas dataframe
data = pd.read_csv('./kingcounty_house_data.csv')

In [5]:
data.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900.0         3       1.00         1180   
1  6414100192  20141209T000000   538000.0         3       2.25         2570   
2  5631500400  20150225T000000   180000.0         2       1.00          770   
3  2487200875  20141209T000000   604000.0         4       3.00         1960   
4  1954400510  20150218T000000   510000.0         3       2.00         1680   
5  7237550310  20140512T000000  1225000.0         4       4.50         5420   
6  1321400060  20140627T000000   257500.0         3       2.25         1715   
7  2008000270  20150115T000000   291850.0         3       1.50         1060   
8  2414600126  20150415T000000   229500.0         3       1.00         1780   
9  3793500160  20150312T000000   323000.0         3       2.50         1890   

   sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0      5650     1.0           0     0          3      7        1180   
1      7242     2.0           0     0          3      7        2170   
2     10000     1.0           0     0          3      6         770   
3      5000     1.0           0     0          5      7        1050   
4      8080     1.0           0     0          3      8        1680   
5    101930     1.0           0     0          3     11        3890   
6      6819     2.0           0     0          3      7        1715   
7      9711     1.0           0     0          3      7        1060   
8      7470     1.0           0     0          3      7        1050   
9      6560     2.0           0     0          3      7        1890   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   
5           1530      2001             0    98053  47.6561 -122.005   
6              0      1995             0    98003  47.3097 -122.327   
7              0      1963             0    98198  47.4095 -122.315   
8            730      1960             0    98146  47.5123 -122.337   
9              0      2003             0    98038  47.3684 -122.031   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  
5           4760      101930  
6           2238        6819  
7           1650        9711  
8           1780        8113  
9           2390        7570

In [6]:
data.shape

(21613, 21)

In [7]:
price=data.price

In [8]:
price.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [9]:
data.drop("price",1,inplace=True)

In [10]:
Id=data.id

In [11]:
data.drop("id",1,inplace=True)

In [12]:
data.drop("date",1,inplace=True)

In [13]:
data.head(10)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   
2         2       1.00          770     10000     1.0           0     0   
3         4       3.00         1960      5000     1.0           0     0   
4         3       2.00         1680      8080     1.0           0     0   
5         4       4.50         5420    101930     1.0           0     0   
6         3       2.25         1715      6819     2.0           0     0   
7         3       1.50         1060      9711     1.0           0     0   
8         3       1.00         1780      7470     1.0           0     0   
9         3       2.50         1890      6560     2.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   
2          3      6         770              0      1933             0   
3          5      7        1050            910      1965             0   
4          3      8        1680              0      1987             0   
5          3     11        3890           1530      2001             0   
6          3      7        1715              0      1995             0   
7          3      7        1060              0      1963             0   
8          3      7        1050            730      1960             0   
9          3      7        1890              0      2003             0   

   zipcode      lat     long  sqft_living15  sqft_lot15  
0    98178  47.5112 -122.257           1340        5650  
1    98125  47.7210 -122.319           1690        7639  
2    98028  47.7379 -122.233           2720        8062  
3    98136  47.5208 -122.393           1360        5000  
4    98074  47.6168 -122.045           1800        7503  
5    98053  47.6561 -122.005           4760      101930  
6    98003  47.3097 -122.327           2238        6819  
7    98198  47.4095 -122.315           1650        9711  
8    98146  47.5123 -122.337           1780        8113  
9    98038  47.3684 -122.031           2390        7570

In [14]:
data.bedrooms.unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33])

In [15]:
data.bathrooms.unique()

array([ 1.  ,  2.25,  3.  ,  2.  ,  4.5 ,  1.5 ,  2.5 ,  1.75,  2.75,
        3.25,  4.  ,  3.5 ,  0.75,  4.75,  5.  ,  4.25,  3.75,  0.  ,
        1.25,  5.25,  6.  ,  0.5 ,  5.5 ,  6.75,  5.75,  8.  ,  7.5 ,
        7.75,  6.25,  6.5 ])

In [16]:
data.sqft_living.unique()

array([1180, 2570,  770, ..., 3087, 3118, 1425])

In [17]:
data[data.sqft_living.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [18]:
data[data.sqft_lot.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [19]:
data[data.floors.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [20]:
data[data.waterfront.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [21]:
data.waterfront.unique()

array([0, 1])

In [22]:
data[data.view.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [23]:
data.view.unique()

array([0, 3, 4, 2, 1])

In [24]:
data[data.condition.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [25]:
data[data.grade.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [26]:
data[data.sqft_above.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [27]:
data[data.yr_built.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [28]:
data[data.yr_renovated.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [29]:
data[data.lat.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [30]:
data[data.long.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [31]:
data[data.sqft_living15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [32]:
data[data.sqft_lot15.isnull()]

Empty DataFrame
Columns: [bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

In [33]:
data.drop("sqft_living15",1,inplace=True)

In [34]:
data.drop("sqft_lot15",1,inplace=True)

In [35]:
# data.drop("grade",1,inplace=True)

In [36]:
data.drop("waterfront",1,inplace=True)

In [37]:
# data.drop("sqft_above",1,inplace=True)

In [38]:
train = data.ix[0:15000]
test= data.ix[15001:]

In [39]:
target_value=  price

In [40]:
target_value.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [41]:
target=target_value[0:15001]

In [42]:
target.shape

(15001,)

In [43]:
train.shape

(15001, 15)

In [44]:
test.shape

(6612, 15)

In [45]:
start=time.time()

In [46]:
clf = RandomForestClassifier(n_estimators=25)

In [47]:
clf=clf.fit(train, target)

In [48]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

bedrooms  :  0.040659651088
bathrooms  :  0.0542372113322
sqft_living  :  0.108753643948
sqft_lot  :  0.12009496431
floors  :  0.0199120834561
view  :  0.0146432489167
condition  :  0.0355256396886
grade  :  0.0252670317795
sqft_above  :  0.107684932809
sqft_basement  :  0.0493625816158
yr_built  :  0.103190645318
yr_renovated  :  0.0102441738025
zipcode  :  0.0720882753336
lat  :  0.123200321604
long  :  0.115135594998


In [49]:
Output = clf.predict(test)


In [50]:
end=time.time()

In [51]:
elapsed = end - start
print(elapsed)

55.65992712974548


In [52]:
homeId=Id[15001:]

In [53]:
homeId.shape

(6612,)

In [54]:
result = pd.DataFrame(columns=['Id', 'price'])

In [55]:
result['Id'] = homeId
result['price'] = Output.astype(int)

In [56]:
# result.drop("Sprice",1,inplace=True)

In [57]:
result.to_csv('HousingPrice.csv', index=False)

In [58]:
print(result.head(10)) 

               Id    price
15001  7504021310   615000
15002  7504021310   615000
15003  8024201795   235000
15004  8638500170   350000
15005  5437400630   625000
15006  9264000010   400000
15007  3832600080   240000
15008  9477001350   445950
15009   809001060  1325000
15010  2771604120  1015000


In [59]:
ground_truth=target_value[15001:]

In [60]:
ground_truth.shape

(6612,)

In [61]:
mean_squared_error(ground_truth,result.price)

45224023009.014519

In [62]:
accuracy_score(ground_truth,result.price)

0.0102843315184513

In [63]:
mean_absolute_error(ground_truth,result.price,multioutput='raw_values')

array([ 111542.83484574])

In [64]:
Resultant = pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [65]:
Resultant['ground_truth']=ground_truth

In [66]:
Resultant['Estimated']=result['price']

In [67]:
print(Resultant.head(20))

       ground_truth  Estimated
15001      525000.0     615000
15002      745000.0     615000
15003      397000.0     235000
15004      233000.0     350000
15005      625000.0     625000
15006      535000.0     400000
15007      270000.0     240000
15008      360000.0     445950
15009     1105000.0    1325000
15010      970000.0    1015000
15011      915000.0     850000
15012      412000.0     385000
15013      265000.0     260000
15014      426000.0     425000
15015      266000.0     229000
15016      325000.0     549000
15017      615000.0     496752
15018      310000.0     263500
15019      340000.0     423000
15020      562500.0     409950


In [68]:
total=Resultant['ground_truth'].sum()

In [69]:
total_estimated=Resultant['Estimated'].sum()

In [70]:
print(abs(total_estimated-total)/total)

0.0852007705603403


In [71]:
# x = Resultant['ground_truth']
# y = Resultant['Estimated']
# plt.plot(x, y)


## APPLYING RANDOMIZATION

In [72]:
df=pd.read_csv('./kingcounty_house_data.csv')


In [73]:
sample_data=df.take(np.random.permutation(len(df))[:2500])

In [74]:
sample_data.head(10)

id             date     price  bedrooms  bathrooms  \
15818  8699100321  20140611T000000  292000.0         4       2.75   
14265  7683800212  20141218T000000  229000.0         3       1.00   
16957  2464400285  20141229T000000  575000.0         3       2.50   
16603  4406000050  20140519T000000  225000.0         2       1.00   
8235   1257202215  20140714T000000  810000.0         4       1.75   
16894  1231000895  20141105T000000  986000.0         4       3.50   
16291  7855600080  20150330T000000  750000.0         3       1.75   
7120   6055000430  20150327T000000  473000.0         4       3.50   
8305   3791410210  20141117T000000  473000.0         5       3.50   
12301  8682292090  20140709T000000  737000.0         2       2.25   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
15818         2414      7693     2.0           0     0          3      8   
14265         1010     12705     1.0           0     0          4      7   
16957         1590      2910     2.0           0     0          3      7   
16603          910      9612     1.0           0     0          4      7   
8235          1760      4080     1.5           0     0          4      8   
16894         2840      5900     2.0           0     0          3     10   
16291         2770     15232     1.0           0     0          3      8   
7120          4370     37193     2.0           0     3          3      8   
8305          3430      6872     2.0           0     0          3     10   
12301         2290      9772     1.0           0     0          3      8   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
15818        2414              0      2006             0    98002  47.3046   
14265        1010              0      1959             0    98003  47.3348   
16957        1110            480      1984             0    98115  47.6855   
16603         910              0      1981             0    98058  47.4297   
8235         1760              0      1906             0    98103  47.6750   
16894        1920            920      1910          2008    98118  47.5543   
16291        1570           1200      1976             0    98006  47.5706   
7120         2780           1590      1996             0    98022  47.2410   
8305         2830            600      2002             0    98031  47.4065   
12301        2290              0      2007             0    98053  47.7199   

          long  sqft_living15  sqft_lot15  
15818 -122.222           1500        7177  
14265 -122.303           1490       10200  
16957 -122.321           1590        3880  
16603 -122.152           1410        9611  
8235  -122.331           1760        6120  
16894 -122.268           1300        4900  
16291 -122.160           2340       11400  
7120  -121.979           2860       39356  
8305  -122.207           3650        6600  
12301 -122.025           1810        6077

In [75]:
sample_price=sample_data.price

In [76]:
sample_price.head()

15818    292000.0
14265    229000.0
16957    575000.0
16603    225000.0
8235     810000.0
Name: price, dtype: float64

In [77]:
train, test = train_test_split(sample_data, test_size = 0.3)

In [78]:
train_price=train.price

In [79]:
test_price=test.price

In [80]:
train.drop("price",1,inplace=True)

In [81]:
train.drop("date",1,inplace=True)

In [82]:
train.drop("waterfront",1,inplace=True)

In [83]:
train.drop("sqft_living15",1,inplace=True)

In [84]:
train.drop("sqft_lot15",1,inplace=True)

In [85]:
test.drop("price",1,inplace=True)

In [86]:
test.drop("date",1,inplace=True)

In [87]:
test.drop("waterfront",1,inplace=True)

In [88]:
test.drop("sqft_living15",1,inplace=True)

In [89]:
test.drop("sqft_lot15",1,inplace=True)

In [90]:
start=time.time()

In [91]:
clf = RandomForestClassifier()

In [92]:
clf=clf.fit(train, train_price)

In [93]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.10446423183
bedrooms  :  0.0356358465386
bathrooms  :  0.0550474627594
sqft_living  :  0.0954353359661
sqft_lot  :  0.104315230019
floors  :  0.0221202952163
view  :  0.0131802035557
condition  :  0.0271043546261
grade  :  0.0341263078326
sqft_above  :  0.0918979366963
sqft_basement  :  0.0372784357064
yr_built  :  0.0910090743161
yr_renovated  :  0.00965826108723
zipcode  :  0.0773598453402
lat  :  0.101162905669
long  :  0.100204272841


In [94]:
Output = clf.predict(test)

In [95]:
end=time.time()

In [96]:
elapsed = end - start
print(elapsed)

1.3721919059753418


In [97]:
# tree.export_graphviz(clf,out_file='tree.dot')

In [98]:
Random_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [99]:
Random_Result['ground_truth']=test_price

In [100]:
Random_Result['Estimated']=Output.astype(int)

In [101]:
# print(Random_Result.head(10))

In [102]:
mean_squared_error(test_price,Random_Result['Estimated'])

61653418112.042664

In [103]:
mean_absolute_error(test_price,Random_Result['Estimated'])

155194.32000000001

In [104]:
print(Random_Result.head(20))

       ground_truth  Estimated
10706      456700.0     285000
3339       265000.0     200000
13161      790000.0     450000
5008       805000.0     720000
2129       330000.0     188000
12817      242500.0     293000
15162      930000.0     340000
13835      245000.0     390000
10828      653750.0     676000
9282       665000.0     540000
4620       270000.0     203000
7456       486000.0     451000
1352       585000.0     525000
7433      1600000.0    1815000
19002      385000.0     188000
14350      525000.0     650000
1748       451555.0     406650
3348       675000.0     300523
8057       550000.0     303000
11892      432000.0     235000


In [105]:
total=Random_Result['ground_truth'].sum()

In [106]:
total_estimated=Random_Result['Estimated'].sum()

In [107]:
print(abs(total_estimated-total)/total)

0.16391954314028656


## Without Randomization

In [108]:
df=pd.read_csv('./kingcounty_house_data.csv')

In [109]:
data=df[:2500]

In [110]:
price=data.price

In [111]:
train, test = train_test_split(data, test_size = 0.3)

In [112]:
train_price=train.price

In [113]:
test_price=test.price

In [114]:
train.drop("price",1,inplace=True)

In [115]:
train.drop("date",1,inplace=True)

In [116]:
train.drop("waterfront",1,inplace=True)

In [117]:
train.drop("sqft_living15",1,inplace=True)

In [118]:
train.drop("sqft_lot15",1,inplace=True)

In [119]:
test.drop("price",1,inplace=True)

In [120]:
test.drop("date",1,inplace=True)

In [121]:
test.drop("waterfront",1,inplace=True)

In [122]:
test.drop("sqft_living15",1,inplace=True)

In [123]:
test.drop("sqft_lot15",1,inplace=True)

In [124]:
start=time.time()

In [125]:
clf = RandomForestClassifier()

In [126]:
clf=clf.fit(train, train_price)

In [127]:
for header, value in zip(train.columns,clf.feature_importances_):
    print (header," : ", value)

id  :  0.101146954939
bedrooms  :  0.0392167173031
bathrooms  :  0.0501026439702
sqft_living  :  0.0918895868669
sqft_lot  :  0.103743507356
floors  :  0.0183963379189
view  :  0.0153513920313
condition  :  0.0288210494203
grade  :  0.0358822636939
sqft_above  :  0.0943518270271
sqft_basement  :  0.0475786873048
yr_built  :  0.0903384805877
yr_renovated  :  0.0108162898976
zipcode  :  0.0698955546258
lat  :  0.102755914225
long  :  0.0997127928329


In [128]:
Output = clf.predict(test)

In [129]:
end=time.time()

In [130]:
elapsed = end - start
print(elapsed)

0.8901479244232178


In [131]:
Subset_Result=pd.DataFrame(columns=['ground_truth', 'Estimated'])

In [132]:
Subset_Result['ground_truth']=test_price

In [133]:
Subset_Result['Estimated']=Output.astype(int)

In [134]:
print(Subset_Result.head(20))

      ground_truth  Estimated
1200      254000.0     262000
2085     3850000.0    1928000
1474      280000.0     283500
418       355000.0     382000
1745      541100.0     475000
205       840000.0     340000
1059      425000.0     254000
365       465000.0     437000
507       442000.0     325000
1028      245000.0     245000
1005      563000.0     545000
51        345000.0     469500
1743      508000.0     552500
277       770000.0     597326
437       843000.0     837700
1866      475000.0     330000
59        430000.0     327500
674       385000.0     390000
0         221900.0     260000
1869      668000.0     630000


In [135]:
total=Subset_Result['ground_truth'].sum()

In [140]:
Subset_Result[['ground_truth','Estimated']]

ground_truth  Estimated
1200      254000.0     262000
2085     3850000.0    1928000
1474      280000.0     283500
418       355000.0     382000
1745      541100.0     475000
205       840000.0     340000
1059      425000.0     254000
365       465000.0     437000
507       442000.0     325000
1028      245000.0     245000
1005      563000.0     545000
51        345000.0     469500
1743      508000.0     552500
277       770000.0     597326
437       843000.0     837700
1866      475000.0     330000
59        430000.0     327500
674       385000.0     390000
0         221900.0     260000
1869      668000.0     630000
1486      229950.0     280000
2274      299500.0     365000
1975      200000.0     190000
2267     2750000.0     835000
396       530000.0     403500
2247      600000.0     662000
1974      420000.0     252000
320       819900.0     802541
1052     1050000.0     917500
334       940000.0     420000
434       525000.0     439000
1115      262000.0     345000
380       270000.0     210000
81        360000.0     308000
1315     5300000.0    5110800
292       360000.0     262000
139       519950.0     280000
1684      700000.0     395000
1648      272750.0     235000
1917      210000.0     230000
690       373000.0     500000
549       215000.0     170000
234       475000.0     378000
1524      405000.0     495000
335       260000.0     300000
289       500000.0     390000
1568      789500.0     735000
361       380000.0     340000
1682      390000.0     230000
1820      275000.0     315000
...            ...        ...
1076      310000.0     284000
531       200000.0     219000
415       570000.0     600000
1665      662990.0     570000
1061     1035480.0     780000
2314     1400000.0     975000
52        600000.0     700000
1599      455000.0     451555
892       395000.0     325000
149       511000.0     495000
1071      360000.0     436000
62        505000.0     340000
582       730000.0     570000
395       330000.0     340895
499       437500.0     430000
1657      400000.0     200000
867       457500.0     310000
1770     2350000.0     614000
276       450000.0     500000
846       664000.0     250000
1630      180500.0     269000
1689      467000.0     280000
2116      345000.0     279000
1856      339000.0     338900
324       232000.0     240500
1118      353000.0     260000
1389      275000.0      75000
1225      365000.0     605000
1999      722500.0     580000
2048      545000.0     605000
1316      595000.0     566000
994       178500.0     245000
862       539900.0     305000
220       686000.0     625000
259       693000.0     655000
519       890000.0     390000
812       347000.0     320000
1925      467000.0     524250
2301      370000.0     350000
2322      450000.0     365000
989       484950.0     500000
869       289999.0     220000
1546      365000.0     390000
789       408200.0     250000
343       309600.0     288349
2176      760000.0     730000
342       425000.0     535000
2193      760000.0     503000
229       516500.0     400000
2066      460000.0     425000

[750 rows x 2 columns]

In [137]:
total_estimated=Subset_Result['Estimated'].sum()

In [138]:
print(abs(total_estimated-total)/total)

0.20770542457692023
